### ISSUE TITLE
Courses in the web app are different

### ISSUE THREAD

**Issue by mastazi** [open-source-society/data-science#3]
The Readme says that I can track my progress in the web app ("my progress" tab) however there are different courses there, e.g. the data science track features Calculus from EdX and MIT but in the web app there is only calculus from Coursera. Am I missing something?

**Comment by ericdouglas** [comment]
@mastazi sorry for the mistake. The app is, actually, for the [Computer Science](https://github.com/open-source-society/computer-science) path.
