### ISSUE TITLE
Add official badge

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/data-science#7]
Maybe we can put an official badge in this repository, so students will be able to link back to this in their own projects.

Example: [![Open Source Society University - Data Science](https://img.shields.io/badge/OSSU-data--science-blue.svg)](https://github.com/open-source-society/data-science)
- Markdown: `[![Open Source Society University - Data Science](https://img.shields.io/badge/OSSU-data--science-blue.svg)](https://github.com/open-source-society/data-science)`
- HTML: `<a href="https://github.com/open-source-society/data-science"><img alt="Open Source Society University - Data Science" src="https://img.shields.io/badge/OSSU-data--science-blue.svg"></a>`

:smile:

**Comment by royshouvik** [comment]
Thanks @ericdouglas , I will add the badge and some project ideas to the repo.

**Comment by mdibaiee** [comment]
@royshouvik I would love to add the badge to my projects, too!

**Comment by royshouvik** [comment]
Closing this as I added the badge to the course repo. @mdibaiee you can just copy paste the Markdown/HTML snippet mentioned above anywhere you want to use the badge.
